export enum OrderStatusEnums {
  PAGAMENTO = 'PAGAMENTO',
  CANCELADO = 'CANCELADO',
  FILA = 'FILA',
  PRODUCAO = 'PRODUCAO',
  EXPEDICAO = 'EXPEDICAO',
  ENTREGA = 'ENTREGA',
  RETORNO = 'RETORNO',
  FINALIZADO = 'FINALIZADO',
}
