export enum RolesEnums {
  ADMINISTRADOR = 'ADMINISTRADOR',
  FINANCEIRO = 'FINANCEIRO',
  RECEPCAO = 'RECEPCAO',
  EXPEDICAO = 'EXPEDICAO',
  PRODUCAO = 'PRODUCAO',
  ENTREGADOR = 'ENTREGADOR',
  CLIENTE = 'CLIENTE',
}
